[2024-07-05T14:33:49.730358+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:33:49.736673+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:33:49.736689+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:33:49.807002+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:33:49.852873+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:33:51.756280+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:33:51.757206+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:33:51.757221+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:33:51.763867+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:33:51.787400+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:33:53.560465+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:33:53.561348+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:33:53.561363+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:33:53.568437+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:33:53.576873+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:33:55.356948+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:33:55.357834+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:33:55.357850+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:33:55.365269+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:33:55.374032+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:36:40.789308+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:36:40.796696+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:36:40.796715+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:36:40.874282+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:36:40.898142+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:36:43.038676+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:36:43.039609+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:36:43.039626+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:36:43.046680+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:36:43.055560+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:36:44.955644+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:36:44.956684+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:36:44.956702+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:36:44.965277+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:36:44.974322+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:36:46.750958+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:36:46.751841+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:36:46.751857+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:36:46.758811+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:36:46.767453+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:39:32.045799+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:39:32.046746+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:39:32.046761+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:39:32.126845+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:39:32.153337+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:39:34.272408+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:39:34.273304+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:39:34.273320+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:39:34.280328+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:39:34.305289+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:39:36.695162+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:39:36.696001+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:39:36.696016+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:39:36.702923+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:39:36.724586+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:39:38.627979+00:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost/login","method":"POST"} []
[2024-07-05T14:39:38.629163+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:39:38.629179+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:39:38.636357+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-07-05T14:39:38.659693+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-07-05T14:59:11.095845+00:00] request.INFO: Matched route "app_user_list". {"route":"app_user_list","route_parameters":{"_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::urlRedirectAction","path":"/admin/user/","permanent":true,"scheme":null,"httpPort":80,"httpsPort":443,"_route":"app_user_list"},"request_uri":"http://localhost/admin/user","method":"GET"} []
[2024-07-05T14:59:11.110418+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-07-05T14:59:11.110450+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:59:11.110480+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-07-05T14:59:11.125209+00:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:87)"} []
[2024-07-05T14:59:11.125718+00:00] security.DEBUG: Calling Authentication entry point. {"entry_point":{"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator":[]}} []
[2024-07-05T14:59:11.162852+00:00] php.CRITICAL: Fatal Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsRedirected cannot extend readonly class PHPUnit\Framework\Constraint\Constraint {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsRedirected cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsRedirected.php:17)"} []
[2024-07-05T14:59:11.172431+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsRedirected cannot extend readonly class PHPUnit\Framework\Constraint\Constraint" at ResponseIsRedirected.php line 17 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsRedirected cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsRedirected.php:17)"} []
[2024-08-21T17:23:02.044323+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-08-21T17:23:02.065631+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-08-21T17:23:02.065653+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:23:02.065674+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:23:02.168317+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-08-21T17:23:02.194460+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-21T17:23:03.117688+00:00] php.CRITICAL: Fatal Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:23:03.118120+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint" at ResponseIsSuccessful.php line 17 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:26:27.552790+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-08-21T17:26:27.574356+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-08-21T17:26:27.574377+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:26:27.574395+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:26:27.664584+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-08-21T17:26:27.711988+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-21T17:26:28.594369+00:00] php.CRITICAL: Fatal Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:26:28.594794+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint" at ResponseIsSuccessful.php line 17 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:29:03.148751+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-08-21T17:29:03.168471+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-08-21T17:29:03.168490+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:29:03.168506+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:29:03.282933+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-08-21T17:29:03.327467+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-21T17:29:04.228964+00:00] php.CRITICAL: Fatal Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:29:04.229317+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint" at ResponseIsSuccessful.php line 17 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:30:48.245217+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-08-21T17:30:48.255808+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-08-21T17:30:48.255823+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:30:48.255838+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:30:48.307935+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-08-21T17:30:48.342799+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-21T17:30:49.203224+00:00] php.CRITICAL: Fatal Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:30:49.203566+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint" at ResponseIsSuccessful.php line 17 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:32:07.602899+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-08-21T17:32:07.613560+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-08-21T17:32:07.613578+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:32:07.613594+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:32:07.666188+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-08-21T17:32:07.679838+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-21T17:32:08.551980+00:00] php.CRITICAL: Fatal Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:32:08.552340+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Non-readonly class Symfony\Component\HttpFoundation\Test\Constraint\ResponseIsSuccessful cannot extend readonly class PHPUnit\Framework\Constraint\Constraint" at ResponseIsSuccessful.php line 17 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Non-readonly class Symfony\\Component\\HttpFoundation\\Test\\Constraint\\ResponseIsSuccessful cannot extend readonly class PHPUnit\\Framework\\Constraint\\Constraint at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\symfony\\http-foundation\\Test\\Constraint\\ResponseIsSuccessful.php:17)"} []
[2024-08-21T17:39:40.266003+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-08-21T17:39:40.285779+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-08-21T17:39:40.285797+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:39:40.285815+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:39:40.375838+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-08-21T17:39:40.403852+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-21T17:54:40.805492+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-08-21T17:54:40.824566+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-08-21T17:54:40.824583+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:54:40.824599+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T17:54:40.917215+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-08-21T17:54:40.948826+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-21T18:26:29.027465+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-08-21T18:26:29.047741+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-08-21T18:26:29.047758+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T18:26:29.047774+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T18:26:29.144368+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-08-21T18:26:29.160971+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-21T18:46:49.288953+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-08-21T18:46:49.311853+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-08-21T18:46:49.311893+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T18:46:49.311920+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-08-21T18:46:49.402324+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"driver":"pdo_mysql","use_savepoints":true,"dbname_suffix":"_test","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_db_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-08-21T18:46:49.418465+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Base 'arcadia_db_test' inconnue at C:\\wamp64\\www\\studi-ecf-arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
